server {
    listen [::]:443 ssl default_server;
    listen 443 ssl default_server;

    server_name app.poxp.shop 45.55.40.101.nip.io 45.55.40.101;

    root /var/www/frontend/dist;
    index index.html;
    ssl_certificate /etc/letsencrypt/live/app.poxp.shop/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/app.poxp.shop/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    client_max_body_size 100M;

    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_types text/plain text/css text/xml application/json application/javascript application/rss+xml application/atom+xml image/svg+xml;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass https://api.poxp.shop/api/;
        proxy_ssl_server_name on;
        proxy_set_header Host api.poxp.shop;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        client_max_body_size 100M;
        proxy_connect_timeout 120s;
        proxy_send_timeout 120s;
        proxy_read_timeout 120s;
    }

    location /assets/ {
        expires 1y;
        add_header Cache-Control "public, no-transform";
    }
}

server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name app.poxp.shop 45.55.40.101.nip.io 45.55.40.101;

    client_max_body_size 100M;

    location /.well-known/acme-challenge/ {
        root /var/www/frontend/dist;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}
